#!/bin/bash

#SBATCH --job-name=meegflow
#SBATCH --ntasks-per-node=10
#SBATCH --mem=10G
#SBATCH --time=00:15:00

# Copyright (c) 2026 brainlife.io
#
# This is the main file run by the brainlife.io orchestration system
#
# Author: Maximilien Chaumon

set -e
set -x

# Run the actual python code
singularity exec docker://ghcr.io/brainlifemeeg/meegflow:latest python3 main.py
